-- =============================================
-- Author:		RTG
-- Create date: 7/2020
-- Description:	Reset Tier and days to retain history
-- =============================================
CREATE PROCEDURE [job].[RESET_TierAndHistoryForJob] 
AS
BEGIN


UPDATE [JobMonitorV2].[job].[Details]
set tier = 1 
, DaysOfHistoryToRetain = 3
where jobname = 'TMS_SetOrderStatus'
or jobname ='SendKochAppNotifications_5Min'
or jobname ='TMSIntegration_FromTMS_5m'
or jobname ='TMSIntegration_FromTMS'
or jobname ='3GTMS_ReprocessLockedOrders'
or jobname ='AutoReleaseFreezeLots_5m'



UPDATE [JobMonitorV2].[job].[Details]
set tier = 2
, DaysOfHistoryToRetain = 3
where jobname = 'LoadJobStatus_10min'
or jobname ='TMSIntegration_ToTMS_15m'
or jobname ='WLM_DirectLabor_15min'
or jobname ='WLM_IndirectLabor_10min'
or jobname ='DW_ProductLots_2Hr_0100'
or jobname ='PreactorStaging_0515'
or jobname ='TMSIntegration_ToTMS'
or jobname ='WLM_DirectLabor_15min'
or jobname ='WLM_IndirectLabor_10Min'
or jobname ='TMS_SetOrderStatus'
or jobname ='CorrrectTemperDate_10Min'
or jobname ='CorrectTemperDate_10min'
or jobname ='HO_XferFiles_15min'
or jobname ='FixScheduledShipDates_XX15'
or jobname ='Preactor_InTransitInventories_0405_15min'
or jobname ='FixScheduledShipDates_XX15'
or jobname ='LoadPELines_30Min'
or jobname ='CanopyBackups.HalfHourLogs'


UPDATE [JobMonitorV2].[job].[Details]
set tier = 3
, DaysOfHistoryToRetain = 3
where jobname = 'CustomerARData'
or jobname ='DW_Orders_2 hrs'
or jobname ='DW_ProductLots_2Hr_0100'
or jobname ='DW-Orders-2 Hrs'
or jobname ='DW-ProductGroupings- 0430'
or jobname ='CustomerARData'
or jobname ='DW_Orders_2 hrs'
or jobname ='DW-Customers-2Hrs'
or jobname ='UpdateOrderGrossWgts'
or jobname ='C2CInventories'
or jobname ='C2CInventories_0430_1hr'
or jobname ='FairfieldAdvanceDayStart_0500'
or jobname ='LoadPELines_30m'
or jobname ='ProductLineInfo_Hourly0410'
or jobname ='ProductLineInfo_0410_1hr'

UPDATE [JobMonitorV2].[job].[Details]
set tier = 4
, DaysOfHistoryToRetain = 4
where jobname = 'AdvanceDayStart_0600'
or jobname ='AdvanceDayStart_2300'
or jobname ='DailyInventory_0500'
or jobname ='DW_Customers_0530'
or jobname ='DW_ProductionHistory_0210'
or jobname ='DW_Products_0430'
or jobname ='DW_SalesHistory_0200'
or jobname ='DW-Koch_MiscData'
or jobname ='PreactorStaging_0515'
or jobname ='zzz_TestJob'
or jobname ='DailyInventory_0500'
or jobname ='DW_Customers_0530'
or jobname ='DW_Products_0430'
or jobname ='DW_SalesHistory'
or jobname ='DW_SalesHistory_0200'
or jobname ='DW-ProductGroupings- 0430'
or jobname ='DW_APChecks_2000'
or jobname ='DW_ApInvAcc_2045'
or jobname ='DW_APTrans_1915'
or jobname ='DW_CPSumHist_2100'
or jobname ='DW_CustGrp_0320'
or jobname ='DW_CustMstr_1730'
or jobname ='DW_CustomerClass_1700'
or jobname ='DW_DailyInventory_0600'
or jobname ='DW_DetHist_0200'
or jobname ='DW_GLAcctAmts_1730'
or jobname ='DW_GLCOA_1700'
or jobname ='DW_GLPerAccts_1715'
or jobname ='DW_GLTrans_2045'
or jobname ='DW_LotsLastYear_0015'
or jobname ='DW_OrderCustomFields_1740'
or jobname ='DW_OrderODPairs_0545'
or jobname ='DW_Orders_0230'
or jobname ='DW_POAndMsgs_1745'
or jobname ='DW_PrdGrouping_0330'
or jobname ='DW_ProdCat_1730'
or jobname ='DW_ProdMstr_0230'
or jobname ='DW_ProductCustomFields_1740'
or jobname ='DW_Rebates_1400'
or jobname ='DW_Salesman_1800'
or jobname ='DW_Vendors_1630'
or jobname ='DW_WarehouseInfo_2330'
or jobname ='FixScheduledShipDates_4xDaily'
or jobname ='SetPOReceiptsInvoicedFlag_0500'
or jobname ='HistorySummary_0600'
or jobname ='PreactorStaging_0515'
or jobname ='EnableShippingContainers_0600'
or jobname ='FPRBuild_0400'
or jobname ='InventoryExceptions_0945'
or jobname ='TrailerCoop_PullAzure'
or jobname ='TrailerCoop_PullTrailerAndInspectionData'
or jobname ='TrailerCoop_PushPurchaseOrderDataToAzure'
or jobname= 'ProdPlannerExtract_0545_1045'

UPDATE [JobMonitorV2].[job].[Details]
set tier = 5
, DaysOfHistoryToRetain = 5
where jobname = 'CanopyBackups_01.CanopyCleanup'
or jobname ='CanopyBackups_01.Data Backups'
or jobname ='CanopyBackups_01.Log Backups'
or jobname ='MidnightInventorySnapshot'
or jobname ='TrgBackups.NonCritData'
or jobname ='TrgBackups.NonCriticalCleanup'
or jobname ='TrgBackups.NonCritLogs'
or jobname ='WingRandomDataBuild_1615'
or jobname ='CanopyBackups_01.CanopyCleanup'
or jobname ='CanopyBackups_01.CanopyData'
or jobname ='CanopyBackups_01.CanopyLogs'
or jobname ='MidnightInventory'
or jobname ='TrgBackups.Cleanup'
or jobname ='TrgBackups.Data'
or jobname ='TrgBackups.Logs'
or jobname ='CanopyBackups.CanopyCleanup'
or jobname ='CanopyBackups.CanopyData'
or jobname ='CanopyBackups.CanopyLogs'
or jobname ='CanopyBackups_02.Data Backups'
or jobname ='CanopyBackups_02.Log Backups'
or jobname ='MidnightInventorySnapshot'
or jobname ='NonCriticalBackups.NonCritialLogs'
or jobname ='NonCriticalBackups.NonCriticalCleanup'
or jobname ='NonCriticalBackups.NonCriticalData'
or jobname ='SystemDBs_02.SystemDBBackups'
or jobname ='WingRandomDataBuild_1615'
or jobname ='CanopyBackups_02.CanopyCleanup'
or jobname ='CanopyBackups_02.CanopyData'
or jobname ='CanopyBackups_02.CanopyLogs'
or jobname ='TrgBackups.NonCritCleanup'
or jobname ='TrgBackups.NonCritData'
or jobname ='TrgBackups.NonCritLogs'
or jobname ='AdvanceDayStart_000'
or jobname ='AdvanceDayStart_0300'
or jobname ='DBBackups.DBBackups'
or jobname ='Forge_LoadCustomers_0103'
or jobname ='Forge_LoadInvoiceData_0110'
or jobname ='Forge_LoadProducts_0105'
or jobname ='Forge_LoadVendors_0100'
or jobname ='JobMonitorV2'
or jobname ='JobMonitorV2_CompileData'
or jobname ='JobMonitorV2_PurgeData'
or jobname ='LogBackups.Subplan_1'
or jobname ='NonCritical.Data'
or jobname ='NonCritical.Logs'
or jobname ='TMSIntegtration_Cleanup_2145'
or jobname ='DBnLogBackups.Database Backups'
or jobname ='DBnLogBackups.LogBackups'
or jobname ='DW_ProductionHistory'
or jobname ='DW_ProductionHistory_0210'
or jobname ='DW-Koch_MiscData'
or jobname ='Forge_LoadCustomers_0103'
or jobname ='Forge_LoadInvoiceData_0110'
or jobname ='Forge_LoadProducts_0105'
or jobname ='Forge_LoadVendors_0100'
or jobname ='TMSIntegtration_Cleanup'
or jobname ='CanopyBackups_01.DailyBackups'
or jobname ='CanopyBackups_01.LogBackups'
or jobname ='CleanUp_01.Canopy Cleanup'
or jobname ='CleanUp_01.NonCriticalCleanup'
or jobname ='CleanUp_01.SystemCleanup'
or jobname ='NonCritBackups.NonCritData'
or jobname ='NonCritBackups.NonCritLogs'
or jobname ='CanopyBackups_02.WeeklyBackups'
or jobname ='CanopyBackups_02.Log Backups'
or jobname ='CanopyBackups_02.Daily Data'
or jobname ='CanopyBackups_02.Clean Up'
or jobname ='3GTMS_ReprocessLockedOrders'
or jobname ='SystemBackups.SystemDBData'
or jobname ='ProdPlannerMorning_0545'
or jobname ='ProdPlannerMidDay_1045'
or jobname ='MidnightInventorySnapshot_0001'
or jobname ='FixScheduledShipDates_0230'
or jobname ='CanopyBackups.Log'
or jobname ='CanopyBackups.Database'
or jobname ='MidnightInventorySnapshot'
or jobname ='Backups.System'
or jobname ='Backups.NonCritLogs'
or jobname ='Backups.NonCritData'
or jobname ='Backups.Logs'
or jobname ='Backups.Clean Up'
or jobname ='Backups.Canopy Data'
or jobname ='AdvanceDayStart_0200'
or jobname ='TrailerCoop_PushRoles'
or jobname ='TrailerCoop_PurgeData'
or jobname ='AdvanceDayStart_0001'
or jobname ='AdvanceDayStart_0300'
or jobname ='AdvanceDayStart_2300'
or jobname ='SystemDBs.SystemLogs'
or jobname ='NonCritBackups.Cleanup'
or jobname ='AutoInsertExceptions'
or jobname ='Backups.Daily Data'
or jobname ='SystemBackups.SystemLogs'
or jobname ='SystemDBs.SystemDBs'
or jobname ='Backups.NonCritBackups'
or jobname ='Backups.Log Backups'
or jobname ='Backups.System Backups'
or jobname ='Non_Critical.SystemLogs'
or jobname ='Non_Critical.NonCriticalCleanup'
or jobname ='Non_Critical.SystemCleanup'
or jobname ='CanopyBackps.Canopy Logs'
or jobname ='Non_Critical.SystemData'
or jobname ='Non_Critical.NonCriticalLogs'
or jobname ='Non_Critical.NonCriticalData'
or jobname ='CanopyBackps.Cleanup'
or jobname ='CanopyBackps.Daily Data'
or jobname ='Non_Critical.SystemClean'
or jobname ='CanopyBackups.CleanUp'
or jobname ='CanopyBackups.DailyData'

UPDATE [JobMonitorV2].[job].[Details]
set tier = 6
, DaysOfHistoryToRetain = 20
where jobname = 'WingRandomDataBuild_Thursday_1615'

UPDATE [JobMonitorV2].[job].[Details]
set tier = 7
, DaysOfHistoryToRetain = 20
where jobname = 'WingRandomDataBuild_Friday_1615'


UPDATE [JobMonitorV2].[job].[Details]
set tier = 8
, DaysOfHistoryToRetain = 20
where jobname = 'SystemBackps_01.DataBackups'
or jobname ='SystemBackps_01.LogBackups'
or jobname ='SystemBackps_01.SystemCleanup'
or jobname ='System.SystemCleanup'
or jobname ='System.SystemData'
or jobname ='System.SystemLogs'
or jobname ='SystemBackups.LogBackups'
or jobname ='SystemBackups.SystemCleanup'
or jobname ='SystemBackups.SystemData'
or jobname ='OptimizeIndexes'
or jobname ='Integrity.Integrity'
or jobname ='SystemDBs.System Cleanup'
or jobname ='SystemDBs.System Data'
or jobname ='SystemDBs.System Logs'
or jobname ='DBCCCheckDB_Sun1400'
or jobname ='DBCCCheckDB_Sun_1400'
or jobname ='Maint_OptimizeIndexes'
or jobname ='Weekly.WeeklyBackups'


END